### ISSUE TITLE
Cannot convert 1525016070 rdb dataset to ms

### ISSUE THREAD

**Issue by sirothia** [ska-sa/katdal#147] opened 2018-05-08 10:23 UTC
Unable to convert
http://stgr1.sdp.mkat.chpc.kat.ac.za:7480/1525016070/1525016070_sdp_l0.full.rdb
dataset to ms, whereas it is possible to convert dataset just before and after this.
The error it pasted below:

Traceback (most recent call last):
  File "/usr/local/bin/mvftoms.py", line 800, in <module>
Using 'pyrap' casacore binding to produce MS
Accessing http://archive-gw-1.kat.ac.za:7480//auth.html
Extract MS for spw 0: central frequency 1284.00 MHz
Will create MS output in 1525016070.ms

#### Producing a full polarisation MS (HH,HV,VH,VV) ####

Cross-correlations only.

Using m047 as the reference antenna. All targets and activity detection will be based on this antenna.

Iterating through scans in file(s)...

Writing static meta data...
scan   1 (   8 samples) loaded. Target: 'J0742-1459'. Writing to disk...
    main()
  File "/usr/local/bin/mvftoms.py", line 522, in main
    scan_vis_data, scan_weight_data, scan_flag_data)
  File "/usr/local/bin/mvftoms.py", line 64, in load
    [vis, weights, flags], lock=False)
  File "/usr/local/lib/python2.7/dist-packages/dask/array/core.py", line 949, in store
    result.compute(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dask/base.py", line 154, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dask/base.py", line 407, in compute
    results = get(dsk, keys, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/usr/local/lib/python2.7/dist-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python2.7/dist-packages/dask/local.py", line 270, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/usr/local/lib/python2.7/dist-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/usr/local/lib/python2.7/dist-packages/katdal/chunkstore_s3.py", line 140, in get_chunk
    response = self.client.get_object(Bucket=bucket, Key=key)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/katdal/chunkstore.py", line 364, in _standard_errors
    raise StandardisedError(prefix + str(e))
katdal.chunkstore.ChunkNotFound: "Chunk u'1525016070_sdp_l0/weights_channel/00003_01024': An error occurred (NoSuchKey) when calling the GetObject operation: Unknown"

**Comment by ludwigschwardt** [comment] 2018-05-08 10:32
That looks like a missing chunk in the archive. I'm working on a fix for this that should be out by the end of the week. We should just check whether there are more missing chunks or if this is an isolated case.

If you are impatient, just add the option `--quack=4` to `mvftoms` and you should hopefully be fine.

**Comment by lmzxqtom** [comment] 2018-05-08 11:16
@ludwigschwardt I can confirm that the  chunk is in the store: s3://1522237642_sdp_l0/weights_channel/00003_01024.npy

**Comment by lmzxqtom** [comment] 2018-05-08 11:27
@ludwigschwardt good call. Sorry paste error.

Correct - s3cmdl ls s3://1525016070_sdp_l0/weights_channel/00003* only matches one file:
s3://1525016070_sdp_l0/weights_channel/00003_00000.npy

**Comment by bmerry** [comment] 2018-09-20 06:13
katdal now deals gracefully with missing chunks in the archive (they're flagged), so I'm going to close this. Reopen if it's still a problem.

**Closed by bmerry** 2018-09-20 06:13 UTC
